#!/usr/bin/env bash

# install dracula gtk theme

# just for arch?
if [ ! -d $tela ]
then
    mkdir -p ~/src
    git clone git@github.com:vinceliuice/Tela-icon-theme.git $tela
    /home/chad/src/Tela-icon-theme/install.sh -a
fi
