#!/usr/bin/env bash

{% if yadm.class == "Arch" %}
# install dracula gtk theme

tela="/tmp/Tela-icon-theme"
if [ ! -d $tela ]
then
    git clone git@github.com:vinceliuice/Tela-icon-theme.git $tela
    $tela/install.sh -a
fi

{% endif %}
